# Generated by Django 3.1.3 on 2021-01-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
