# Generated by Django 3.1.3 on 2021-01-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='created_at',
        ),
    ]
